import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mahedi Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-screen h-screen bg-gradient-to-b from-blue-50 to-blue-200">
          <div className="w-screen h-24">
            <Navbar />
          </div>
          <div className="w-screen h-[calc(100vh-96px)]">
            {children}
          </div>

        </div>
      </body>
    </html>
  );
}
